[package]
name = "ip-sniffer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
bpaf = { version = "0.9.9", features = ["derive", "bright-color"] }
